//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminUser
    {    [Display(Name ="Mã User")]
        public int ID { get; set; }
        [Required(ErrorMessage ="Name not emty.....")]
        [StringLength(25,ErrorMessage ="UserName khong duoc qua 25 ky tu")]
       
        public string NameUser { get; set; }
        [StringLength(10,ErrorMessage =" roleuser khong duoc qua 10 ky tu")]
       
        public string RoleUser { get; set; }
        [StringLength(50,ErrorMessage ="password khong qua 50 ky tu")]
        
        public string PasswordUser { get; set; }
    }
}
